### ISSUE TITLE
How to prevent to remove the old version build files in blob storage when using Teams toolkit to deploy tabs to blob storage?

### ISSUE THREAD

**Issue by XYjourney** [OfficeDev/teams-toolkit-samples#509]
When I update my code and deploy latest code using Teams Toolkit, it always removes the old version built files  in blob storage and upload the new built files, but I want to reserve the old files except the same name files.

![image](https://user-images.githubusercontent.com/18476675/195862803-76dd139d-40fa-4880-a73d-0e41c90c6ca2.png)
![image](https://user-images.githubusercontent.com/18476675/195863395-02a8dcf2-c4c7-4660-973d-bac13b9dc4fd.png)

**Comment by hund030** [comment]
Deleting the old artifact is still a default behavior in the latest Teams Toolkit. Since there are some files will conflict between each version, for example, index.html. 
I am going to close this issue since it has been too long... sorry to that. If there is still requirement to reserve these file, please reopen the issue.
